name: feature_discovery
description: >-
  A Flutter package that implements Material Design Feature discovery
  to show a description of specific features to new users.
  See https://tinyurl.com/FeatureDiscovery
version: 0.14.1
homepage: https://github.com/ayalma/feature_discovery

environment:
  # This should match the Flutter stable SDK constraint.
  # See https://github.com/flutter/flutter/blob/stable/packages/flutter/pubspec.yaml.
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  

dependency_overrides:
  # TODO(creativecreatorormaybenot): Remove when Pedantic is updated in flutter_test.
  
